language: node_js
node_js:
  - node

jobs:
  include:
    - stage: test
      name: "Test"
      script: yarn test
    - name: "Build"
      script: yarn build

    - stage: deploy
      name: "Build and Deploy"
      script: yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        on:
          branch: master
        local-dir: build
